project:
  type: book

book:
  title: "Data Engineer Notes"
  author: "Kittipos Sirivongrungson"
  repo-url: https://github.com/Lightbridge-KS/data-engineer-notes
  site-url: https://data-engineer-notes-lightbridge.netlify.app
  date: today
  chapters:
    - index.qmd
    - part: System Architecture
      chapters: 
        - text: Event-driven vs Task/Batch processing
          href: "contents/data_architect/event-driven-vs-task-based.qmd"
        - text: Task/Batch Processing Tech
          href: "contents/data_architect/batch-task-tech.qmd"
        - text: Event Driven Tech
          href: "contents/data_architect/event-driven-tech.qmd"
    - part: Data Solution
      chapters: 
        - text: OLAP for Radiology
          href: "contents/data_architect/OLAP-radiology-architect.qmd"
        - text: DataHub
          href: "contents/data_architect/datahub.qmd"
    - part: RDW
      chapters: 
        - text: RDW data transfer
          href: "contents/rdw/rdw-data-transfer-naive-to-mature.qmd"
    - part: Data Lake
      chapters: 
        - "contents/minio/minio-cheatsheet.qmd"
    - part: Workflow
      chapters: 
        - text: Apache Airflow
          href: "contents/workflows/apache-airflow.qmd"
        - text: Prefect
          href: "contents/workflows/prefect.qmd"
    - part: Usecases
      chapters: 
        - text: Exchange Zone Brainstorm
          href: "contents/exchange-zone/rama-exchange-zone.qmd"

bibliography: references.bib

format:
  html:
    lightbox: true
    theme:
      light:
        - cosmos
      dark:
        - darkly


